###
GET http://localhost:8000/api/users/getAllUsers


###
GET http://localhost:8000/api/users/getUserByID/1

###
DELETE  http://localhost:8000/api/users/deleteEmployee/1
###//add an employee

POST http://localhost:8000/api/users/addNewEmployee
Content-Type: application/json

{
    "FirstName": "John",
    "LastName": "pop",
    "Location": "New York",
    "BirthDate": "1998-01-01",
    "Contact": "1234564508",
    "Gender": "male",
    "admin": false,
    "PositionID": 2,
    "ScheduleID": 1,
    "PhotoURL": "https://example.com/photo.jpg",
    "Email": "pop@example.com",
    "Password": "password",
    "BankName": "Example Bank",
    "BankBranch": "New York Branch",
    "AccountNumber": "1234567780",
    "Bio": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla at fermentum diam."
}
###
PUT http://localhost:8000/api/users/UpdateEmployeeByID/9
Content-Type: application/json

{
    "EmployeeID": 1,
    "FirstName": "Don",
    "LastName": "doe",
    "Location": "York",
    "BirthDate": "1998-01-01T00:00:00.000Z",
    "Contact": "1234564508",
    "Gender": "male",
    "admin": false,
    "PositionID": 1,
    "ScheduleID": 1,
    "PhotoURL": "https://example.com/photo.jpg",
    "Email": "oe@example.com",
    "Password": "password",
    "BankName": "Example Bank",
    "BankBranch": "New York Branch",
    "AccountNumber": "1234567780",
    "Bio": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla at ferme"
}
  
###//add an employee
POST http://localhost:8000/api/users/login
Content-Type: application/json

{
  "Email": "john.doe@example.com",
  "Password": ""
}


PUT http://localhost:8000/api/UpdateEmployeeByID/
Content-Type: application/json

{

}

/////////---------------position--------------------------------------------------------------------////////
### 
GET  http://localhost:8000/api/position/all

###
POST http://localhost:8000/api/position/addPosition
Content-Type: application/json

{
  "PositionDescription": " Web developer",
  "GrossSalary": 7000
}


###
PATCH  http://localhost:8000/api/position/1
Content-Type: application/json

{
  "PositionDescription": "Developer",
  "GrossSalary": 7000
}



###
DELETE http://localhost:8000/api/position/3



////------------------------------cashadvance-------------------------------------------/////////
###
GET http://localhost:8000/api/getAll/cashAdvance


### 
POST http://localhost:8000/api/create/cashAdvance
content-Type: application/json

{
  "employeeID": 12,
  "amount": 5000.00
}




### Deleting a single user
DELETE  http://localhost:8000/api//cashadvances/

### 
PUT  http://localhost:8000/api/edit/cashAdvance
content-Type: application/json

{
  "employeeID": 12,
  "amount": 500.00
}



//---------------------------------deductions-------------------------------------------------/////



###
GET http://localhost:8000/api/deductions
### 
POST http://localhost:8000/api/deductions/add
content-Type: application/json

{
    "description":"Medical Insurance",
    "amount":100.50,
    "employeeID":1
}



### Deleting a single user
DELETE  http://localhost:8000/api/deductions/

### 
PUT http://localhost:8000/api/14
content-Type: application/json

 {
  

 
}



//----------------------------------------schedule---------------------------------//////


###
GET http://localhost:8000/api/schedule/employee


###
GET http://localhost:8000/api/schedule/1/employees



### Add
POST http://localhost:8000/api/schedule/addSchedule
content-Type: application/json

{
  "InTime": "01:00:00", 
  "OutTime": "7:00:00",
  "ScheduleName": "morning Shift"
}

### 
PUT http://localhost:8000/api/schedule/update/1
content-Type: application/json

  {
    "InTime": "02:00:00", 
    "OutTime": "16:00:00",
    "ScheduleName": "Eve Shift"
  }


###
DELETE  http://localhost:8000/api/schedule/remove/6
### 



//-----------------------------overtime---------------------------------------------


GET http://localhost:8000/api/overtime/getall
### 
GET http://localhost:8000/api/


### Deleting a single user
DELETE  http://localhost:8000/api/

### 
POST http://localhost:8000/api/overtime/add
Content-Type: application/json

{
  "number_of_hours":5,
  "rate_per_hours":15.5,
  "employeeID":12
}


PUT  http://localhost:8000/api/
content-Type: application/json



////----------------------------------Attendance----------------------------////

### get all Attendance
GET http://localhost:8000/api/attendance/getAll 

### get Attendance By ID.
GET http://localhost:8000/api/attendance/getattendanceByID/14

### Delete Attendance .
DELETE http://localhost:8000/api/attendance/deleteattendanceByID/4



### Add New Attendance
POST http://localhost:8000/api/attendance/addAttendance
Content-Type: application/json

{
    "EmployeeID": 12,
    "Date": "2024-03-18",
    "ScheduleID": 1,
    "TimeIn": "08:00:AM",
    "TimeOut": "14:00:pm",
    "Hours": "6"
}

### Update Attendance
PUT http://localhost:8000/api/attendance/editAttendance/6
Content-Type: application/json

{
    "EmployeeID": 2,
    "Date": "2024-03-18T00:00:00.000Z",
    "ScheduleID": 1,
    "TimeIn": "1970-01-01T08:00:00.000Z",
    "TimeOut": "14:00:00.000Z",
    "Hours": "6"
}